language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g grunt-cli
after_success: grunt release
before_deploy: echo 'ready?'
deploy:
  provider: releases
  api_key:
    secure: W5kwsHMWpoH36mqSn3XkAxTIzRke59vdIbP/AsHRShVTg4yr5Nbb/vpKq9PLvAlr8fjNAuOr09SXXvezvW1EZb0NMxY/LLIFfo7+L72zxKZtR65yLUwqRwI9fV77Yo1IrKtVytRohMdxcs2rWes23hey2Vt97Lzo8rJT+PU5isk=
  file: release/vector2d-lib.min.js
  on:
    repo: vinceallenvince/vector2d-lib
    tags: true
    all_branches: true
after_deploy:
- echo 'done!'
- ./deploy-gh-pages.sh
env:
  global:
  - GH_REF: github.com/vinceallenvince/vector2d-lib.git
  - secure: EZY89AVPmycOQ1G/9y+vE6JBtr5bI9TFVpg5EiJvCnBX3FGTdFSoffMHZSjrwkSnSd1bPqO+NmWpgDbGaGuzaTyuddU6bEZPEH6CuKsS7cvMaTQ7kFlc3cMo8Q9qdHy6fzJ9HSCHZszPNScs4/XP9Yt6IKupzIiroUSDNHZzzpA=
